### ISSUE TITLE
DLC Limitation

### ISSUE THREAD

**Issue by gravefunc** [mehrdad987/stm32-NMEA2000#1]
data Length = rxHeader.DLC;
it all the time equal to 8 and data corrupted for length bigger than 8

**Comment by mehrdad987** [comment]
Yes, it works for DLCs smaller than 8 because of the CAN standard. but let me check if there is a way

**Comment by mehrdad987** [comment]
> data Length = rxHeader.DLC; it all the time equal to 8 and data corrupted for length bigger than 8

TRY this--reduce the rate of receiving
